= Funções da aplicação
:allow-uri-read: 




== Funções da aplicação

As funções de aplicativo fornecem acesso a aplicativos do BlueXP , como o consultor digital do Active IQ (também conhecido como consultor digital).



=== Administrador de storage

Fornece ao usuário a capacidade de executar funções de administração de storage no BlueXP , como atualizações de software e criação e exclusão de ambientes de trabalho do BlueXP .

Permissões:: Pode visualizar a tela BlueXP . Pode criar e gerenciar conetores BlueXP . Tem acesso de leitura/gravação às funções de governança e integridade do storage do BlueXP , incluindo:
+
--
* Consultor digital
* Resiliência operacional
* Atualizações de software (pode executar atualizações de software)
* Carteira digital
* Eficiência económica
* Painel de sustentabilidade
* Alertas


--




=== Visualizador de armazenamento

Fornece acesso somente leitura às funções de saúde e governança do BlueXP . Essa função geralmente é atribuída a usuários que são responsáveis pelo monitoramento da integridade dos recursos de armazenamento de uma organização. Os usuários com essa função podem visualizar várias aplicações no BlueXP  para criar planos de atualização de software e planos de eficiência, bem como visualizar a integridade geral do storage.

Permissões:: Tem acesso somente leitura às funções de governança e integridade do storage do BlueXP , incluindo:
+
--
* Consultor digital
* Resiliência operacional
* Atualizações de software (pode transferir planos de atualização)
* Carteira digital
* Eficiência económica
* Painel de sustentabilidade
* Alertas


--


Exemplo de tarefa: Por exemplo, se você tiver sete na hierarquia de recursos representando os respetivos projetos (ambientes de trabalho) dentro deles, poderá atribuir a alguém a função de administrador de armazenamento para três dos projetos e atribuir a um membro diferente o administrador de armazenamento para os projetos restantes. Outra possibilidade seria atribuir a um usuário a função de administrador de armazenamento para toda a organização. Você pode gerenciar as funções dos membros de acordo com as necessidades de sua organização.
