---
sidebar: sidebar 
permalink: concept-connectors.html 
keywords: 'concept, connectors, learn about connectors, what are connectors, what is a connector, what"s a connector, days, 14 days, when is a connector required, connector supported locations, restricted mode, private mode, dark site, permissions, multiple connectors, disaster recovery' 
summary: Um conetor é o software NetApp executado em sua rede na nuvem ou na rede local. Ele executa as ações que o BlueXP  precisa executar para gerenciar sua infraestrutura de dados. O conetor constantemente pesquisa a camada SaaS do BlueXP  para quaisquer ações que ele precise tomar. Você não precisa de um conetor para começar a usar o BlueXP , mas precisará criar um conetor para desbloquear todos os recursos e serviços do BlueXP . 
---
= Saiba mais sobre conetores
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Um _Connector_ é um software NetApp executado em sua rede na nuvem ou na rede local. Ele executa as ações que o BlueXP  precisa executar para gerenciar sua infraestrutura de dados. O conetor constantemente pesquisa a camada de software como serviço (SaaS) da BlueXP  para qualquer ação que precise ser executada. Você não precisa de um conetor para começar a usar o BlueXP , mas precisará criar um conetor para desbloquear todos os recursos e serviços do BlueXP .



== O que você pode fazer sem um conetor

Não é necessário um conetor para começar a usar o BlueXP . Você pode usar vários recursos e serviços no BlueXP  sem nunca criar um conetor.

Você pode usar os seguintes recursos e serviços do BlueXP  sem um conetor:

* Criação do ambiente de trabalho do Amazon FSX for NetApp ONTAP
+
Embora um conetor não seja necessário para criar um ambiente de trabalho, ele precisa criar e gerenciar volumes, replicar dados e integrar o FSX for ONTAP com serviços como classificação BlueXP  e cópia e sincronização do BlueXP .

* Catálogo de automação
* Azure NetApp Files
+
Embora um conetor não seja necessário para configurar e gerenciar Azure NetApp Files, um conetor é necessário se você quiser usar a classificação BlueXP  para digitalizar dados Azure NetApp Files.

* Cloud Volumes Service para Google Cloud
* Copiar e sincronizar
* Consultor digital
* Carteira digital
+
Em quase todos os casos, você pode adicionar uma licença à carteira digital sem um conetor.

+
A única vez que um conetor é necessário para adicionar uma licença à carteira digital é para licenças Cloud Volumes ONTAP _node-based_. Neste caso, é necessário um conetor porque os dados são retirados das licenças instaladas em sistemas Cloud Volumes ONTAP.

* Detecção direta de clusters ONTAP no local
+
Embora um conetor não seja necessário para a descoberta direta de um cluster ONTAP no local, um conetor é necessário se você quiser aproveitar os recursos adicionais do BlueXP .

+
https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-discovering-ontap.html["Saiba mais sobre as opções de descoberta e gerenciamento para clusters ONTAP no local"^]

* Atualizações de software
* Sustentabilidade




== Quando é necessário um conetor

Quando você usa o BlueXP  no modo padrão, um conetor é necessário para os seguintes recursos e serviços no BlueXP :

* Alertas
* Recursos de gerenciamento do Amazon FSX for ONTAP
* Storage Amazon S3
* Storage Azure Blob
* Backup e recuperação
* Classificação
* Cloud Volumes ONTAP
* Recuperação de desastres
* Sistemas e-Series
* Eficiência econômica 1
* Buckets do Google Cloud Storage
* Integração de clusters ONTAP no local com serviços de dados BlueXP 
* Resiliência operacional 1
* Proteção contra ransomware
* Sistemas StorageGRID
* Disposição em camadas
* Armazenamento em cache de volume


1 enquanto você pode acessar esses serviços sem um conetor, um conetor é necessário para iniciar ações a partir dos serviços.

É necessário um conetor para utilizar o BlueXP  no modo restrito ou no modo privado.



== Os conetores devem estar sempre operacionais

Os conetores são uma parte fundamental da arquitetura de serviços do BlueXP . É da sua responsabilidade garantir que os conetores relevantes estejam sempre ativos, operacionais e acessíveis. Embora o serviço seja projetado para superar interrupções curtas da disponibilidade do conetor, você precisa tomar medidas imediatas quando necessário para solucionar falhas de infraestrutura.

Esta documentação é regida pelo EULA. Se o produto não for operado de acordo com a documentação, a funcionalidade e o funcionamento do produto, bem como os seus direitos ao abrigo do EULA, podem ser afetados negativamente.



=== Impacto no Cloud Volumes ONTAP

Um conetor é um componente chave na integridade e funcionamento do Cloud Volumes ONTAP. Se um conetor for desligado, os sistemas Cloud Volumes ONTAP PAYGO e os sistemas BYOL baseados em capacidade serão desligados após perder a comunicação com um conetor por mais de 14 dias. Isso acontece porque o conetor atualiza o licenciamento no sistema todos os dias.

Se o seu sistema Cloud Volumes ONTAP tiver uma licença BYOL baseada em nós, o sistema permanecerá em execução após 14 dias porque a licença é instalada no sistema Cloud Volumes ONTAP.



== Locais suportados

Um conetor é suportado nos seguintes locais:

* Amazon Web Services
* Microsoft Azure
+
Um conetor no Azure deve ser implantado na mesma região do Azure que os sistemas Cloud Volumes ONTAP que gerencia, ou no https://docs.microsoft.com/en-us/azure/availability-zones/cross-region-replication-azure#azure-cross-region-replication-pairings-for-all-geographies["Par de regiões do Azure"^] para os sistemas Cloud Volumes ONTAP. Esse requisito garante que uma conexão com o Azure Private Link seja usada entre o Cloud Volumes ONTAP e suas contas de armazenamento associadas. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-enabling-private-link.html["Saiba como o Cloud Volumes ONTAP usa um link privado do Azure"^]

* Google Cloud
+
Se você quiser usar os serviços do BlueXP  com o Google Cloud, use um conetor em execução no Google Cloud.

* No local




== Comunicação com fornecedores de nuvem

O conetor usa o TLS 1,2 para todas as comunicações com a AWS, o Azure e o Google Cloud.



== Modo restrito e modo privado

Para usar o BlueXP  no modo restrito ou no modo privado, você começa a usar o BlueXP  instalando o conetor e acessando a interface do usuário que está sendo executada localmente no conetor.

link:concept-modes.html["Saiba mais sobre os modos de implantação do BlueXP"].



== Como criar um conetor

Você pode criar um conetor diretamente do BlueXP , a partir do mercado do seu provedor de nuvem ou instalando manualmente o software em seu próprio host Linux. A forma como começar depende se está a utilizar o BlueXP  no modo padrão, no modo restrito ou no modo privado.

* link:concept-modes.html["Saiba mais sobre os modos de implantação do BlueXP"]
* link:task-quick-start-standard-mode.html["Comece a usar o BlueXP  no modo padrão"]
* link:task-quick-start-restricted-mode.html["Comece a usar o BlueXP  no modo restrito"]
* link:task-quick-start-private-mode.html["Comece a usar BlueXP  no modo privado"]




== Permissões

Permissões específicas são necessárias para criar o conetor diretamente do BlueXP  e outro conjunto de permissões é necessário para a própria instância do conetor. Se você criar o conetor na AWS ou no Azure diretamente do BlueXP , o BlueXP  criará o conetor com as permissões de que ele precisa.

Ao usar o BlueXP  no modo padrão, a forma como você fornece permissões depende de como você planeja criar o conetor.

Para saber como configurar permissões, consulte o seguinte:

* Modo padrão
+
** link:concept-install-options-aws.html["Opções de instalação do conetor na AWS"]
** link:concept-install-options-azure.html["Opções de instalação do conetor no Azure"]
** link:concept-install-options-google.html["Opções de instalação do conetor no Google Cloud"]
** link:task-install-connector-on-prem.html#step-4-set-up-cloud-permissions["Configurar permissões de nuvem para implantações locais"]


* link:task-prepare-restricted-mode.html#step-6-prepare-cloud-permissions["Configurar permissões para o modo restrito"]
* link:task-prepare-private-mode.html#step-6-prepare-cloud-permissions["Configurar permissões para o modo privado"]


Para ver as permissões exatas que o conetor precisa para operações diárias, consulte as seguintes páginas:

* link:reference-permissions-aws.html["Saiba como o conetor usa permissões da AWS"]
* link:reference-permissions-azure.html["Saiba como o conetor usa permissões do Azure"]
* link:reference-permissions-gcp.html["Saiba como o conetor usa as permissões do Google Cloud"]


É da sua responsabilidade atualizar as políticas do conetor à medida que novas permissões são adicionadas nas versões subsequentes. Se novas permissões forem necessárias, elas serão listadas nas notas de versão.



== Atualizações do conetor

Normalmente, atualizamos o software Connector a cada mês para introduzir novos recursos e fornecer melhorias de estabilidade. Embora a maioria dos serviços e recursos na plataforma BlueXP  sejam oferecidos por software baseado em SaaS, alguns recursos dependem da versão do conetor. Isso inclui gerenciamento de Cloud Volumes ONTAP, gerenciamento de cluster do ONTAP no local, configurações e ajuda.

Quando você usa o BlueXP  no modo padrão ou no modo restrito, o conetor atualiza automaticamente seu software para a versão mais recente, desde que tenha acesso de saída à Internet para obter a atualização de software. Se você estiver usando o BlueXP  no modo privado, precisará atualizar manualmente o conetor.

link:task-upgrade-connector.html["Saiba como atualizar manualmente o software do conetor ao usar o modo privado"].



== Manutenção do sistema operacional e VM

Manter o sistema operacional no host do conetor é sua responsabilidade. Por exemplo, você deve aplicar atualizações de segurança ao sistema operacional no host do conetor seguindo os procedimentos padrão da sua empresa para distribuição do sistema operacional.

Observe que você não precisa interromper nenhum serviço no host do conetor ao aplicar pequenas atualizações de segurança.

Se você precisar parar e, em seguida, iniciar a VM do conetor, você deve fazê-lo a partir do console do seu provedor de nuvem ou usando os procedimentos padrão para gerenciamento no local.

<<Os conetores devem estar sempre operacionais,Tenha em atenção que o conetor deve estar sempre operacional>>.



== Vários ambientes de trabalho e conetores

Um conetor pode gerenciar vários ambientes de trabalho no BlueXP . O número máximo de ambientes de trabalho que um único conetor deve gerenciar varia. Depende do tipo de ambiente de trabalho, do número de volumes, da capacidade que está sendo gerenciada e do número de usuários.

Se você tiver uma implantação em grande escala, trabalhe com seu representante da NetApp para dimensionar o ambiente. Se você tiver algum problema ao longo do caminho, entre em Contato conosco usando o bate-papo no produto.

Em alguns casos, você pode precisar apenas de um conetor, mas você pode encontrar-se precisando de dois ou mais conetores.

Aqui estão alguns exemplos:

* Você tem um ambiente multicloud (por exemplo, AWS e Azure) e prefere ter um conetor na AWS e outro no Azure. Cada um gerencia os sistemas Cloud Volumes ONTAP executados nesses ambientes.
* Um provedor de serviços pode usar uma organização da BlueXP  para fornecer serviços para seus clientes, enquanto usa outra organização para fornecer recuperação de desastres para uma de suas unidades de negócios. Cada organização teria conetores separados.

