---
settings:
  name: BlueXP setup and administration
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: pt-br,us-en,de-de,es-es,fr-fr,it-it,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentos de configuração e administração do BlueXP 
    url: "/index.html"
  - title: Notas de lançamento
    entries:
    - title: O que há de novo
      url: "/whats-new.html"
    - title: Limitações conhecidas
      url: "/reference-limitations.html"
    - title: Alterações nos sistemas operacionais Linux suportados
      url: "/reference-connector-operating-system-changes.html"
  - title: Comece agora
    entries:
    - title: Aprenda o básico
      entries:
      - title: BlueXP
        url: "/concept-overview.html"
      - title: Conetores
        url: "/concept-connectors.html"
      - title: Modos de implantação
        url: "/concept-modes.html"
    - title: Comece com o modo padrão
      entries:
      - title: Fluxo de trabalho de introdução
        url: "/task-quick-start-standard-mode.html"
      - title: Prepare a rede para o console BlueXP 
        url: "/reference-networking-saas-console.html"
      - title: Inscreva-se no BlueXP
        url: "/task-sign-up-saas.html"
      - title: Crie um conetor
        entries:
        - title: AWS
          entries:
          - title: Opções de instalação do conetor
            url: "/concept-install-options-aws.html"
          - title: Crie um conetor a partir do BlueXP 
            url: "/task-install-connector-aws-bluexp.html"
          - title: Crie um conetor a partir do mercado
            url: "/task-install-connector-aws-marketplace.html"
          - title: Instale manualmente o conetor
            url: "/task-install-connector-aws-manual.html"
        - title: Azure
          entries:
          - title: Opções de instalação do conetor
            url: "/concept-install-options-azure.html"
          - title: Crie um conetor a partir do BlueXP 
            url: "/task-install-connector-azure-bluexp.html"
          - title: Crie um conetor a partir do mercado
            url: "/task-install-connector-azure-marketplace.html"
          - title: Instale manualmente o conetor
            url: "/task-install-connector-azure-manual.html"
        - title: Google Cloud
          entries:
          - title: Opções de instalação do conetor
            url: "/concept-install-options-google.html"
          - title: Crie um conetor a partir do BlueXP  ou do gcloud
            url: "/task-install-connector-google-bluexp-gcloud.html"
          - title: Instale manualmente o conetor
            url: "/task-install-connector-google-manual.html"
        - title: On-premises
          url: "/task-install-connector-on-prem.html"
      - title: Inscreva-se no BlueXP 
        url: "/task-subscribe-standard-mode.html"
      - title: O que você pode fazer a seguir
        url: "/reference-whats-next.html"
    - title: Comece com o modo restrito
      entries:
      - title: Fluxo de trabalho de introdução
        url: "/task-quick-start-restricted-mode.html"
      - title: Prepare-se para a implantação
        url: "/task-prepare-restricted-mode.html"
      - title: Implante o conetor
        url: "/task-install-restricted-mode.html"
      - title: Inscreva-se no BlueXP 
        url: "/task-subscribe-restricted-mode.html"
      - title: O que você pode fazer a seguir
        url: "/reference-whats-next-restricted-mode.html"
    - title: Comece com o modo privado
      entries:
      - title: Fluxo de trabalho de introdução
        url: "/task-quick-start-private-mode.html"
      - title: Prepare-se para a implantação
        url: "/task-prepare-private-mode.html"
      - title: Implante o conetor
        url: "/task-install-private-mode.html"
      - title: O que você pode fazer a seguir
        url: "/reference-whats-next-private-mode.html"
    - title: Inicie sessão no BlueXP 
      url: "/task-logging-in.html"
  - title: Administrar o BlueXP 
    entries:
    - title: Gerenciamento de identidade e acesso
      entries:
      - title: Saiba mais sobre o BlueXP  IAM
        url: "/concept-identity-and-access-management.html"
      - title: Comece a usar o BlueXP  IAM
        url: "/task-iam-get-started.html"
      - title: Organize seus recursos com pastas e projetos
        url: "/task-iam-manage-folders-projects.html"
      - title: Adicione membros e gerencie suas permissões
        url: "/task-iam-manage-members-permissions.html"
      - title: Gerencie sua hierarquia de recursos
        url: "/task-iam-manage-resources.html"
      - title: Associar um conetor a outras pastas e projetos
        url: "/task-iam-associate-connectors.html"
      - title: Alterne entre organizações, projetos e conetores
        url: "/task-iam-switch-organizations-projects.html"
      - title: Renomeie sua organização
        url: "/task-iam-rename-organization.html"
      - title: Monitorar ou auditar a atividade do IAM
        url: "/task-iam-audit-actions-timeline.html"
      - title: Funções do IAM predefinidas
        url: "/reference-iam-predefined-roles.html"
    - title: Contas BlueXP 
      entries:
      - title: Saiba mais sobre contas
        url: "/concept-netapp-accounts.html"
      - title: Gerencie sua conta do BlueXP 
        url: "/task-managing-netapp-accounts.html"
      - title: Crie outra conta do BlueXP 
        url: "/task-create-account.html"
      - title: Funções de utilizador
        url: "/reference-user-roles.html"
    - title: Federação de identidade
      url: "/concept-federation.html"
    - title: Conetores
      entries:
      - title: Mantenha a VM e o SO
        url: "/task-maintain-connectors.html"
      - title: Instale um certificado assinado pela CA para acesso ao console da Web
        url: "/task-installing-https-cert.html"
      - title: Configure um conetor para usar um servidor proxy
        url: "/task-configuring-proxy.html"
      - title: Exigir o uso de IMDSv2 em instâncias EC2
        url: "/task-require-imdsv2.html"
      - title: Atualize um conetor ao usar o modo privado
        url: "/task-upgrade-connector.html"
      - title: Trabalhe com vários conetores
        url: "/task-manage-multiple-connectors.html"
      - title: Solucione o problema do conetor
        url: "/task-troubleshoot-connector.html"
      - title: Desinstale e remova o conetor
        url: "/task-uninstall-connector.html"
      - title: Configuração padrão
        url: "/reference-connector-default-config.html"
    - title: Credenciais e assinaturas
      entries:
      - title: AWS
        entries:
        - title: Saiba mais sobre credenciais e permissões
          url: "/concept-accounts-aws.html"
        - title: Gerencie credenciais e assinaturas
          url: "/task-adding-aws-accounts.html"
      - title: Azure
        entries:
        - title: Saiba mais sobre credenciais e permissões
          url: "/concept-accounts-azure.html"
        - title: Gerencie credenciais e assinaturas
          url: "/task-adding-azure-accounts.html"
      - title: Google Cloud
        entries:
        - title: Saiba mais sobre projetos e permissões
          url: "/concept-accounts-gcp.html"
        - title: Gerencie credenciais e assinaturas
          url: "/task-adding-gcp-accounts.html"
      - title: Gerencie credenciais NSS associadas a uma organização ou conta do BlueXP
        url: "/task-adding-nss-accounts.html"
      - title: Gerencie credenciais associadas ao seu login no BlueXP 
        url: "/task-manage-user-credentials.html"
    - title: Monitorar operações do BlueXP 
      url: "/task-monitor-cm-operations.html"
  - title: Referência
    entries:
    - title: Permissões
      entries:
      - title: Resumo das permissões
        url: "/reference-permissions.html"
      - title: Permissões da AWS para o conetor
        url: "/reference-permissions-aws.html"
      - title: Permissões do Azure para o conetor
        url: "/reference-permissions-azure.html"
      - title: Permissões do Google Cloud para o conetor
        url: "/reference-permissions-gcp.html"
    - title: Portas
      entries:
      - title: Regras do grupo de segurança do conetor na AWS
        url: "/reference-ports-aws.html"
      - title: Regras do grupo de segurança do conetor no Azure
        url: "/reference-ports-azure.html"
      - title: Regras de firewall do conetor no Google Cloud
        url: "/reference-ports-gcp.html"
      - title: Portas para o conetor on-premise
        url: "/reference-ports-on-prem.html"
  - title: Conhecimento e apoio
    entries:
    - title: Registre-se para obter suporte
      url: "/task-support-registration.html"
    - title: Obtenha ajuda
      url: "/task-get-help.html"
  - title: Avisos legais
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
