---
sidebar: sidebar 
permalink: reference-user-roles.html 
keywords: user, users, roles, role, task, permission, permissions, tasks, admin, Account Admin, Workspace Admin, Cloud Compliance Viewer, Cloud Data Sense, SnapCenter Admin 
summary: As funções Administrador da conta, Administrador do espaço de trabalho, Visualizador de conformidade e Administrador do SnapCenter fornecem permissões específicas aos usuários. Você pode atribuir uma dessas funções ao associar um novo usuário à sua conta do BlueXP . 
---
= Funções de utilizador
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Quando você usa o BlueXP  no modo restrito ou privado, você usará uma conta _BlueXP _ para gerenciar usuários. Você pode fornecer permissões específicas para usuários em sua conta selecionando uma das seguintes funções: Administrador de conta, Administrador do espaço de trabalho, Visualizador de conformidade e Administrador do SnapCenter

Se você estiver usando o BlueXP  no modo padrão, você não terá uma conta do BlueXP . Em vez disso, você terá uma organização _BlueXP _ que você gerencia usando o gerenciamento de identidade e acesso do BlueXP  (IAM).

* link:concept-identity-and-access-management.html["Saiba mais sobre o BlueXP  IAM"]
* link:concept-modes.html["Saiba mais sobre os modos de implantação do BlueXP"]


[cols="24,19,19,19,19"]
|===
| Tarefa | Administrador da conta | Admin da área de trabalho | Visualizador de conformidade | Administrador do SnapCenter 


| Crie conetores | Sim | Não | Não | Não 


| Gerenciar ambientes de trabalho | Sim | Sim | Não | Sim 


| Ativar serviços em ambientes de trabalho | Sim | Sim | Não | Sim 


| Use os serviços do BlueXP  | Sim | Sim | Não | Sim 


| Remover ambientes de trabalho de uma área de trabalho | Sim | Sim | Não | Não 


| Eliminar ambientes de trabalho | Sim | Sim | Não | Não 


| Exibir status de replicação de dados | Sim | Sim | Não | Não 


| Veja a linha do tempo | Sim | Sim | Não | Não 


| Alterne entre espaços de trabalho | Sim | Sim | Sim | Sim 


| Ver os resultados da análise de classificação BlueXP  | Sim | Sim | Sim | Não 


| Receba o relatório Cloud Volumes ONTAP | Sim | Não | Não | Não 


| Gerenciar contas do BlueXP  | Sim | Não | Não | Não 


| Gerenciar credenciais | Sim | Sim | Não | Não 


| Modificar as definições do BlueXP  | Sim | Sim | Não | Não 


| Visualize e gerencie o Painel de suporte | Sim | Sim | Não | Não 
|===
.Link relacionado
link:task-managing-netapp-accounts.html["Gerencie sua conta do BlueXP "]
