---
sidebar: sidebar 
permalink: reference-iam-platform-roles.html 
keywords: predefined roles, iam roles, organization admin, folder or project admin, classification viewer, snapcenter admin, role, iam role, admin, iam, identity and access management 
summary: Atribua funções de plataforma aos usuários para conceder permissões para gerenciar o BlueXP, atribuir funções, adicionar usuários, criar conectores e gerenciar federações. 
---
= Funções de acesso à plataforma BlueXP 
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Atribua funções de plataforma aos usuários para conceder permissões para gerenciar o BlueXP, atribuir funções, adicionar usuários, criar conectores e gerenciar federações.

.Exemplo para funções de organização em BlueXP  para uma grande organização multinacional
A XYZ Corporation organiza o acesso ao armazenamento de dados por região — América do Norte, Europa e Ásia-Pacífico — dando a cada região controle e garantindo supervisão centralizada.

O *administrador da organização* no BlueXP da XYZ Corporation cria uma organização inicial e pastas separadas para cada região. A pasta de cada região contém projetos (com recursos associados) relacionados a essa região. O *administrador da organização* atribui a um usuário do BlueXP  em cada região a função *administrador de pasta ou projeto*.

Administradores regionais com a função *Administrador de pasta ou projeto* gerenciam suas regiões (pastas) adicionando novos recursos e usuários. Esses administradores regionais também podem adicionar, remover ou renomear pastas e projetos que gerenciam. O *Administrador da organização* herda permissões para quaisquer novos recursos, mantendo a visibilidade do uso do armazenamento em toda a organização.

Dentro da mesma organização, um usuário recebe a função *Administrador da Federação* para gerenciar a federação da organização com seu IdP corporativo. Esse usuário pode adicionar ou remover organizações federadas, mas não pode gerenciar usuários ou recursos dentro da organização. A organização atribui a um usuário a função *Visualizador da Federação* para verificar o status da federação e visualizar organizações federadas sem fazer alterações.

As tabelas a seguir indicam as ações que cada função da plataforma BlueXP pode executar.



== Funções de administração da organização

[cols="2,1,1"]
|===
| Tarefa | Administrador da organização | Administrador de pasta ou projeto 


| Crie conetores | Sim | Não 


| Criar, modificar ou excluir ambientes de trabalho (adicionar ou descobrir novos recursos usando a tela BlueXP ) | Sim | Sim 


| Crie pastas e projetos, incluindo exclusão | Sim | Não 


| Renomeie pastas e projetos existentes | Sim | Sim 


| Atribua funções e adicione usuários | Sim | Sim 


| Associar recursos a pastas e projetos | Sim | Sim 


| Associar conetores a pastas e projetos | Sim | Não 


| Remova os conetores de pastas e projetos | Sim | Não 


| Gerenciar conetores (editar certificados, configurações e assim por diante) | Sim | Não 


| Gerir credenciais a partir de Definições > credenciais | Sim | Sim 


| Criar, gerenciar e visualizar federações | Sim | Não 


| Registre-se para obter suporte e enviar casos | Sim | Sim 


| Usar serviços de dados | Sim | Sim 


| Veja o cronograma e as notificações do BlueXP | Sim | Sim 
|===


== Funções da federação

[cols="2,1,1"]
|===
| Tarefa | Administrador da Federação | Visualizador da Federação 


| Criar uma federação | Sim | Não 


| Verificar um domínio | Sim | Não 


| Adicionar um domínio a uma federação | Sim | Não 


| Desabilitar e excluir federações | Sim | Não 


| Federações de teste | Sim | Não 


| Ver federações e seus detalhes | Sim | Sim 
|===