---
sidebar: sidebar 
permalink: reference-iam-predefined-roles.html 
keywords: predefined roles, iam roles, organization admin, folder or project admin, classification viewer, snapcenter admin, role, iam role, admin, iam, identity and access management 
summary: O gerenciamento de identidade e acesso do BlueXP  inclui várias funções predefinidas que podem ser atribuídas aos membros da sua organização. 
---
= Funções e permissões do IAM predefinidas do BlueXP 
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
O BlueXP  Identity and Access Management (IAM) inclui várias funções predefinidas que podem ser atribuídas aos membros da sua organização em diferentes níveis da hierarquia de recursos. Antes de atribuir essas funções, você deve entender as permissões que cada função inclui.



== Funções da plataforma

O BlueXP  IAM inclui duas funções de plataforma: Administrador da organização e administrador de pasta ou projeto. A principal diferença entre as duas funções da plataforma IAM do BlueXP  é o escopo. A função de administrador da organização tem permissões em todas as pastas e projetos; enquanto o administrador da pasta ou do projeto só tem permissões na pasta ou projeto ao qual foram atribuídos.

A função de administrador de pasta ou projeto não pode criar conetores.

Permissões::


[cols="24,19,19"]
|===
| Tarefa | Administrador da organização | Administrador de pasta ou Projeto 


| Crie conetores | Sim | Não 


| Criar, modificar ou excluir ambientes de trabalho (adicionar ou descobrir novos recursos usando a tela BlueXP ) | Sim | Sim 


| Crie projetos/pastas, incluindo renomeação, exclusão e edição | Sim | Sim 


| Atribua funções e adicione usuários | Sim | Sim 


| Associar recursos e conetores a pastas e projetos | Sim | Sim 


| Gerir credenciais a partir de Definições > credenciais | Sim | Sim 


| Veja a linha do tempo do BlueXP  | Sim | Sim 


| Use os serviços do BlueXP  | Sim | Sim 


| Registre o BlueXP  para obter suporte e enviar casos | Sim | Sim 
|===
Exemplo para funções de organização em BlueXP  para uma grande organização multinacional:: A XYZ Corporation, uma empresa multinacional, tem como objetivo separar o acesso a recursos de storage de dados com base em regiões geográficas: América do Norte, Europa e Ásia-Pacífico. Eles querem que cada região tenha controle exclusivo sobre seus recursos, mantendo a supervisão centralizada.
+
--
Para conseguir isso, uma pessoa atribuída à função de administrador da organização no BlueXP  da XYZ Corporation cria um ambiente de trabalho inicial e, em seguida, cria pastas separadas no BlueXP  para cada região. A pasta de cada região contém projetos (com recursos associados) relacionados a essa região. O administrador da organização atribui a um usuário BlueXP  em cada região respetiva a função de administrador de pasta/projeto.

Quando a configuração inicial estiver concluída, os administradores regionais com a função de administrador pasta ou Projeto podem criar novos ambientes de trabalho e adicionar usuários em suas regiões. Esses administradores regionais também podem adicionar/remover/renomear pastas e projetos aos quais são atribuídos. O administrador da organização herda permissões para quaisquer novos ambientes ou recursos de trabalho, mantendo a visibilidade do uso do storage em toda a organização.

--




== Funções de serviços de dados

As funções de serviços de dados podem concluir suas tarefas em qualquer projeto ou pasta.



=== Administrador do SnapCenter

Descrição:: Permite fazer backup de snapshots de clusters ONTAP on-premises usando o backup e a recuperação do BlueXP  para aplicações.
Permissões:: Um membro que tenha essa função pode concluir as seguintes ações no BlueXP :
+
--
* Conclua qualquer ação a partir de cópia de Segurança e recuperação > aplicações
* Gerencie todos os ambientes de trabalho nos projetos e pastas para os quais eles têm permissões
* Use todos os serviços do BlueXP 


--




=== Visualizador de classificação

Descrição:: Fornece os resultados do exame de classificação BlueXP  da vista de capacidade.
Permissões:: Visualize as informações de conformidade e gere relatórios para recursos que eles têm permissão para acessar. Esses usuários não podem ativar ou desativar a digitalização de volumes, buckets ou esquemas de banco de dados.
+
--
Nenhuma outra ação está disponível para um membro que tenha essa função.

--




== Links relacionados

* link:concept-identity-and-access-management.html["Saiba mais sobre o gerenciamento de identidades e acesso do BlueXP "]
* link:task-iam-get-started.html["Comece a usar o BlueXP  IAM"]
* link:task-iam-manage-members-permissions.html["Gerenciar membros do BlueXP  e suas permissões"]
* https://docs.netapp.com/us-en/bluexp-automation/tenancyv4/overview.html["Saiba mais sobre a API para BlueXP  IAM"^]

