---
sidebar: sidebar 
permalink: reference-iam-storage-roles.html 
keywords: predefined roles, iam roles, organization admin, folder or project admin, identity and access management, access roles, admin 
summary: O gerenciamento de identidade e acesso do BlueXP  fornece duas funções administrativas que podem ser atribuídas aos membros da sua organização. 
---
= Funções de acesso ao storage do BlueXP 
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Você pode atribuir as funções a seguir aos usuários para fornecer acesso aos recursos de gerenciamento de storage no BlueXP  associados a recursos de storage compatíveis. Você pode atribuir aos usuários uma função administrativa para gerenciar o armazenamento ou uma função de visualizador para monitoramento.


NOTE: Essas funções não estão disponíveis na API de parceria do BlueXP.

Os administradores podem atribuir funções de armazenamento aos usuários para os seguintes recursos e funcionalidades de armazenamento:

Recursos de armazenamento:

* Clusters ONTAP on-premises
* StorageGRID
* E-Series


Serviços e recursos do BlueXP :

* Consultor digital
* Atualizações de software
* Resiliência operacional
* Eficiência económica
* Sustentabilidade


.Exemplo de funções de storage no BlueXP 
A XYZ Corporation, uma multinacional, tem uma grande equipe de engenheiros de storage e administradores de storage. Eles permitem que essa equipe gerencie ativos de armazenamento para suas regiões, ao mesmo tempo em que limitam o acesso às principais tarefas do BlueXP, como gerenciamento de usuários, criação de conectores e ferramentas de custo, como a carteira digital.

Dentro de uma equipe de 12, dois usuários recebem a função *Visualizador de armazenamento*, que permite monitorar os recursos de armazenamento associados aos projetos BlueXP  aos quais são atribuídos. Os nove restantes recebem a função *administrador de armazenamento*, que inclui a capacidade de gerenciar atualizações de software, acessar o Gerenciador de sistema ONTAP por meio do BlueXP , bem como descobrir recursos de armazenamento (adicionar ambientes de trabalho). Uma pessoa da equipe recebe a função *System Health Specialist* para que possa gerenciar a integridade dos recursos de armazenamento em sua região, mas não modificar ou excluir nenhum ambiente de trabalho. Essa pessoa também pode executar atualizações de software nos recursos de storage para projetos que foram atribuídos.

A organização tem dois usuários adicionais com a função *Administrador da Organização* que podem gerenciar todos os aspetos do BlueXP , incluindo gerenciamento de usuários, criação de conetores e ferramentas de gerenciamento de custos, como carteira digital, bem como vários usuários com a função *Administrador de pasta ou projeto* que podem executar tarefas de administração do BlueXP  para as pastas e projetos aos quais são atribuídos.

A tabela a seguir mostra as ações que cada função de armazenamento do BlueXP executa.

[cols="40,20a,20a,20a"]
|===
| Recurso e ação | Administrador de storage | Especialista em saúde do sistema | Visualizador de armazenamento 


4+| *Canvas*: 


| Descubra novos recursos (crie um novo ambiente de trabalho)  a| 
Sim
 a| 
Sim
 a| 
Não



| Veja os recursos descobertos  a| 
Sim
 a| 
Sim
 a| 
Não



| Eliminar ambientes de trabalho  a| 
Sim
 a| 
Não
 a| 
Não



| Modificar ambientes de trabalho  a| 
Sim
 a| 
Não
 a| 
Não



| *Criar conetor*  a| 
Não
 a| 
Não
 a| 
Não



4+| *Assessor digital* 


| Ver todas as páginas e funções  a| 
Sim
 a| 
Sim
 a| 
Sim



4+| *Carteira digital* 


| Ver todas as páginas e funções  a| 
Não
 a| 
Não
 a| 
Não



4+| *Atualizações de software* 


| Veja a página inicial e as recomendações  a| 
Sim
 a| 
Sim
 a| 
Sim



| Reveja as recomendações de versão potenciais e os principais benefícios  a| 
Sim
 a| 
Sim
 a| 
Sim



| Exibir detalhes da atualização de um cluster  a| 
Sim
 a| 
Sim
 a| 
Sim



| Execute verificações de pré-atualização e transfira o plano de atualização  a| 
Sim
 a| 
Sim
 a| 
Sim



| Instale atualizações de software  a| 
Sim
 a| 
Sim
 a| 
Não



4+| *Resiliência operacional* 


| Analisar problemas de risco de segurança  a| 
Sim
 a| 
Sim
 a| 
Sim



| Baixe playbooks do Ansible  a| 
Sim
 a| 
Sim
 a| 
Não



| Corrija problemas automaticamente  a| 
Sim
 a| 
Sim
 a| 
Não



4+| *Eficiência econômica* 


| Revisar o status do Planejamento de capacidade  a| 
Sim
 a| 
Sim
 a| 
Sim



| Escolha a próxima ação (prática recomendada, nível)  a| 
Sim
 a| 
Não
 a| 
Não



| Armazene dados inativos no storage de nuvem e libere o storage  a| 
Sim
 a| 
Sim
 a| 
Não



| Configure lembretes  a| 
Sim
 a| 
Sim
 a| 
Sim



4+| *Sustentabilidade* 


| Ver painel e recomendações  a| 
Sim
 a| 
Sim
 a| 
Sim



| Transferir dados do relatório  a| 
Sim
 a| 
Sim
 a| 
Sim



| Editar percentagem de mitigação de carbono  a| 
Sim
 a| 
Sim
 a| 
Não



| Corrigir recomendações  a| 
Sim
 a| 
Sim
 a| 
Não



| Adiar recomendações  a| 
Sim
 a| 
Sim
 a| 
Não



4+| *Acesso ao gestor do sistema* 


| Pode introduzir credenciais  a| 
Sim
 a| 
Sim
 a| 
Não



4+| *Credenciais* 


| Credenciais do usuário  a| 
Sim
 a| 
Sim
 a| 
Não

|===