---
sidebar: sidebar 
permalink: task-create-account.html 
keywords: create account, account, create, create another account, tenancy account, tenancy, tenancy account creation 
summary: Ao configurar o BlueXP  no modo restrito ou privado, você será solicitado a criar uma conta. Se você precisar de várias contas, será necessário criá-las usando a API de Tenancy. 
---
= Crie outra conta do BlueXP 
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Ao configurar o BlueXP  no modo privado, você será solicitado a criar uma conta _BlueXP _, que permite gerenciar usuários e organizar recursos. Essa conta pode ser tudo o que você precisa, mas se sua empresa precisar de várias contas, você precisará criar contas adicionais usando a API do Tenancy.

Se você estiver usando o BlueXP  no modo padrão ou restrito, você não terá uma conta do BlueXP . Em vez disso, você terá uma organização que você gerencia usando o gerenciamento de identidade e acesso do BlueXP  (IAM). link:concept-identity-and-access-management.html["Saiba mais sobre o BlueXP  IAM"].

.Passos
. Use a seguinte chamada de API para criar uma conta BlueXP  adicional:
+
POST `/tenancy/account/{accountName}`

+
Se você quiser ativar o modo restrito, você precisa incluir o seguinte no corpo da solicitação:

+
[source, JSON]
----
{
  "isSaasDisabled": true
}
----



NOTE: Você não pode alterar a configuração do modo restrito depois que o BlueXP  criar a conta. Não é possível ativar o modo restrito mais tarde e não é possível desativá-lo mais tarde. Ele deve ser definido no momento da criação da conta.

https://docs.netapp.com/us-en/bluexp-automation/tenancy/post-tenancy-account-id.html["Saiba como usar essa chamada de API"^]

.Informações relacionadas
* link:concept-netapp-accounts.html["Saiba mais sobre as contas do BlueXP "]
* link:concept-modes.html["Saiba mais sobre os modos de implantação do BlueXP"]

