---
sidebar: sidebar 
permalink: task-install-connector-google-manual.html 
keywords: install connector, google cloud connector installation, google cloud connector, install connector in google cloud, bluexp, gcloud, manual install, create connector, gcp installation, gcp connector 
summary: Para instalar manualmente o conetor em seu próprio host Linux, você precisa analisar os requisitos de host, configurar sua rede, preparar permissões do Google Cloud, ativar as APIs do Google Cloud, instalar o conetor e, em seguida, fornecer as permissões que você preparou. 
---
= Instale manualmente o conetor no Google Cloud
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Um conetor é o software NetApp executado em sua rede na nuvem ou na rede local que permite usar todos os recursos e serviços do BlueXP . Uma das opções de instalação disponíveis é instalar manualmente o software Connector em um host Linux executado no Google Cloud. Para instalar manualmente o conetor em seu próprio host Linux, você precisa analisar os requisitos de host, configurar sua rede, preparar permissões do Google Cloud, ativar APIs, instalar o conetor e, em seguida, fornecer as permissões que você preparou.

.Antes de começar
* Você deve ter um link:concept-connectors.html["Compreensão dos conetores"].
* Você deve rever link:reference-limitations.html["Limitações do conetor"].




== Etapa 1: Revise os requisitos do host

O software do conetor deve ser executado em um host que atenda a requisitos específicos do sistema operacional, requisitos de RAM, requisitos de porta, etc.

Host dedicado:: O conetor não é suportado em um host que é compartilhado com outros aplicativos. O host deve ser um host dedicado.
Hipervisor:: É necessário um hypervisor bare metal ou hospedado certificado para executar um sistema operacional suportado.
[[podman-versions]]requisitos de sistema operacional e contentor:: O BlueXP  suporta o conetor com os seguintes sistemas operacionais ao usar o BlueXP  no modo padrão ou no modo restrito. Uma ferramenta de orquestração de contêineres é necessária antes de instalar o conetor.
+
--
[cols="2a,2a,2a,2a,2a"]
|===
| Sistema operacional | Versões de OS compatíveis | Versões de conetor suportadas | Ferramenta de recipiente necessária | SELinux 


 a| 
Red Hat Enterprise Linux
 a| 
9,1 a 9,4

8,6 a 8,10
 a| 
3.9.40 ou posterior com BlueXP  no modo padrão ou modo restrito
 a| 
Podman versão 4.6.1 ou 4.9.4

<<podman-configuration,Veja os requisitos de configuração do Podman>>.
 a| 
Suporte no modo de execução ou modo permissivo 1



 a| 
Ubuntu
 a| 
24,04 LTS
 a| 
3.9.45 ou posterior com BlueXP  no modo padrão ou modo restrito
 a| 
Docker Engine 26.0.0
 a| 
Não suportado



 a| 
22,04 LTS
 a| 
3.9.29 ou posterior
 a| 
Docker Engine 23.0.6 a 26.0.0

26.0.0 é suportado com _new_ Connector 3.9.44 ou instalações posteriores
 a| 
Não suportado

|===
Notas:

. O gerenciamento de sistemas Cloud Volumes ONTAP não é suportado por conetores que tenham o SELinux habilitado no sistema operacional.
. O conetor é suportado em versões em inglês destes sistemas operativos.
. Para o RHEL, o host deve estar registrado no Red Hat Subscription Management. Se não estiver registrado, o host não poderá acessar repositórios para atualizar o software necessário de 3rd partes durante a instalação do conetor.


--
CPU:: 8 núcleos ou 8 vCPUs
RAM:: 32 GB
Tipo de máquina Google Cloud:: Um tipo de instância que atende aos requisitos de CPU e RAM acima. Recomendamos n2-standard-8.
+
--
O conetor é compatível com o Google Cloud em uma instância de VM com um sistema operacional compatível https://cloud.google.com/compute/shielded-vm/docs/shielded-vm["Recursos de VM blindados"^]

--
Espaço em disco em /opt:: 100 GiB de espaço deve estar disponível
+
--
O BlueXP  usa `/opt` para instalar o `/opt/application/netapp` diretório e seu conteúdo.

--
Espaço em disco em /var:: 20 GiB de espaço deve estar disponível
+
--
O BlueXP  requer esse espaço `/var` porque o Docker ou o Podman são arquitetados para criar os contentores dentro desse diretório. Especificamente, eles irão criar contentores no `/var/lib/containers/storage` diretório. Montagens externas ou links simbólicos não funcionam para este espaço.

--




== Passo 2: Instale o Podman ou Docker Engine

Dependendo do seu sistema operacional, o Podman ou o Docker Engine são necessários antes de instalar o conetor.

* O Podman é necessário para o Red Hat Enterprise Linux 8 e 9.
+
<<podman-versions,Veja as versões do Podman suportadas pelo BlueXP >>.

* Docker Engine é necessário para o Ubuntu.
+
<<podman-versions,Veja as versões do Docker Engine que o BlueXP  suporta>>.



.Passos
[role="tabbed-block"]
====
.Podman
--
Siga estas etapas para instalar o Podman e configurá-lo para atender aos seguintes requisitos:

* O serviço podman.socket deve ser ativado e iniciado
* python3 deve ser instalado
* O pacote podman-compose versão 1.0.6 deve ser instalado
* Podman-compose deve ser adicionado à variável de ambiente PATH


.Passos
. Remova o pacote podman-docker se ele estiver instalado no host.
+
[source, cli]
----
dnf remove podman-docker
rm /var/run/docker.sock
----
. Instale o Podman.
+
O Podman está disponível nos repositórios oficiais do Red Hat Enterprise Linux.

+
Para Red Hat Enterprise Linux 9:

+
[source, cli]
----
sudo dnf install podman-2:<version>
----
+
Onde o <version> é a versão suportada do Podman que você está instalando. <<podman-versions,Veja as versões do Podman suportadas pelo BlueXP >>.

+
Para Red Hat Enterprise Linux 8:

+
[source, cli]
----
sudo dnf install podman-3:<version>
----
+
Onde o <version> é a versão suportada do Podman que você está instalando. <<podman-versions,Veja as versões do Podman suportadas pelo BlueXP >>.

. Ative e inicie o serviço podman.socket.
+
[source, cli]
----
sudo systemctl enable --now podman.socket
----
. Instale o python3.
+
[source, cli]
----
sudo dnf install python3
----
. Instale o pacote do repositório EPEL se ainda não estiver disponível no seu sistema.
+
Esta etapa é necessária porque o podman-compose está disponível no repositório extra Packages for Enterprise Linux (EPEL).

+
Para Red Hat Enterprise Linux 9:

+
[source, cli]
----
sudo dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
----
+
Para Red Hat Enterprise Linux 8:

+
[source, cli]
----
sudo dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
----
. Instale o pacote podman-compose 1,0.6.
+
[source, cli]
----
sudo dnf install podman-compose-1.0.6
----
+

NOTE: Usar o `dnf install` comando atende ao requisito para adicionar podman-compose à variável de ambiente PATH. O comando installation adiciona podman-compose ao /usr/bin, que já está incluído na `secure_path` opção no host.



--
.Docker Engine
--
Siga a documentação do Docker para instalar o Docker Engine.

.Passos
. https://docs.docker.com/engine/install/["Veja as instruções de instalação do Docker"^]
+
Certifique-se de seguir as etapas para instalar uma versão específica do Docker Engine. Instalar a versão mais recente irá instalar uma versão do Docker que o BlueXP  não suporta.

. Verifique se o Docker está ativado e em execução.
+
[source, cli]
----
sudo systemctl enable docker && sudo systemctl start docker
----


--
====


== Passo 3: Configurar a rede

Configure sua rede para que o conetor possa gerenciar recursos e processos em seu ambiente de nuvem híbrida. Por exemplo, você precisa garantir que as conexões estejam disponíveis para redes de destino e que o acesso de saída à Internet esteja disponível.

Conexões com redes de destino:: Um conetor requer uma conexão de rede com o local onde você está planejando criar e gerenciar ambientes de trabalho. Por exemplo, a rede em que você planeja criar sistemas Cloud Volumes ONTAP ou um sistema de storage em seu ambiente local.


Acesso de saída à Internet:: O local de rede onde você implantar o conetor deve ter uma conexão de saída de Internet para contatar pontos de extremidade específicos.


Endpoints contatados de computadores ao usar o console baseado na Web do BlueXP :: Os computadores que acessam o console BlueXP  a partir de um navegador da Web devem ter a capacidade de entrar em Contato com vários endpoints. Você precisará usar o console BlueXP  para configurar o conetor e para uso diário do BlueXP .
+
--
link:reference-networking-saas-console.html["Prepare a rede para o console BlueXP "].

--


Terminais contactados durante a instalação manual:: Quando você instala manualmente o conetor em seu próprio host Linux, o instalador do conetor requer acesso aos seguintes URLs durante o processo de instalação:
+
--
* https://mysupport.NetApp.com
* https://signin.b2c.NetApp.com (este endpoint é o URL CNAME para https://mysupport.NetApp.com)
* https://cloudmanager.cloud.NetApp.com/locação
* https://stream.cloudmanager.cloud.NetApp.com
* https://production-artifacts.cloudmanager.cloud.NetApp.com
* \https://*.blob.core.windows.net
* \https://cloudmanagerinfraprod.azurecr.io
+
O host pode tentar atualizar os pacotes do sistema operacional durante a instalação. O host pode entrar em Contato com diferentes sites de espelhamento para esses pacotes do sistema operacional.



--


Terminais contactados a partir do conetor:: O conetor requer acesso de saída à Internet para entrar em Contato com os seguintes endpoints, a fim de gerenciar recursos e processos em seu ambiente de nuvem pública para operações diárias.
+
--
Observe que os endpoints listados abaixo são todas as entradas CNAME.

[cols="2a,1a"]
|===
| Endpoints | Finalidade 


 a| 
\https://www.googleapis.com/compute/v1/ \https://compute.googleapis.com/compute/v1 \https://cloudresourcemanager.googleapis.com/v1/projects \https://www.googleapis.com/compute/beta \https://storage.googleapis.com/storage/v1 \https://www.googleapis.com/storage/v1 \https://iam.googleapis.com/v1 \https://cloudkms.googleapis.com/v1 \https://www.googleapis.com/deploymentmanager/v2/projects
 a| 
Para gerenciar recursos no Google Cloud.



 a| 
https://support.NetApp.com https://mysupport.NetApp.com
 a| 
Para obter informações de licenciamento e enviar mensagens do AutoSupport para o suporte do NetApp.



 a| 
https://*.api.BlueXP .NetApp.com

https://api.BlueXP .NetApp.com

https://*.cloudmanager.cloud.NetApp.com

https://cloudmanager.cloud.NetApp.com

https://NetApp-cloud-account.auth0.com
 a| 
Para fornecer recursos e serviços SaaS no BlueXP .

Observe que o conetor está entrando em Contato atualmente com "cloudmanager.cloud.NetApp.com", mas começará a entrar em Contato com "API.BlueXP .NetApp.com" em uma próxima versão.



 a| 
\https://*.blob.core.windows.net

\https://cloudmanagerinfraprod.azurecr.io
 a| 
Para atualizar o conetor e seus componentes do Docker.

|===
--


Servidor proxy:: Se a sua empresa exigir a implantação de um servidor proxy para todo o tráfego de saída da Internet, obtenha as seguintes informações sobre o proxy HTTP ou HTTPS. Você precisará fornecer essas informações durante a instalação. Observe que o BlueXP  não oferece suporte a servidores proxy transparentes.
+
--
* Endereço IP
* Credenciais
* Certificado HTTPS


--


Portas:: Não há tráfego de entrada para o conetor, a menos que você o inicie ou se o conetor for usado como um proxy para enviar mensagens AutoSupport do Cloud Volumes ONTAP para o suporte da NetApp.
+
--
* HTTP (80) e HTTPS (443) fornecem acesso à IU local, que você usará em circunstâncias raras.
* SSH (22) só é necessário se você precisar se conetar ao host para solução de problemas.
* Conexões de entrada pela porta 3128 são necessárias se você implantar sistemas Cloud Volumes ONTAP em uma sub-rede onde uma conexão de saída à Internet não está disponível.
+
Se os sistemas Cloud Volumes ONTAP não tiverem uma conexão de saída à Internet para enviar mensagens AutoSupport, o BlueXP  configura automaticamente esses sistemas para usar um servidor proxy incluído no conetor. O único requisito é garantir que o grupo de segurança do conetor permita conexões de entrada pela porta 3128. Você precisará abrir essa porta depois de implantar o conetor.



--


Ativar NTP:: Se estiver a planear utilizar a classificação BlueXP  para analisar as suas fontes de dados empresariais, deve ativar um serviço de Protocolo de tempo de rede (NTP) no sistema de conetores BlueXP  e no sistema de classificação BlueXP  para que o tempo seja sincronizado entre os sistemas. https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html["Saiba mais sobre a classificação BlueXP"^]




== Passo 4: Configurar permissões para o conetor

Uma conta de serviço do Google Cloud é necessária para fornecer ao conetor as permissões que o BlueXP  precisa para gerenciar recursos no Google Cloud. Ao criar o conetor, você precisará associar essa conta de serviço à VM do conetor.

É sua responsabilidade atualizar a função personalizada à medida que novas permissões são adicionadas em versões subsequentes. Se novas permissões forem necessárias, elas serão listadas nas notas de versão.

.Passos
. Crie uma função personalizada no Google Cloud:
+
.. Crie um arquivo YAML que inclua o conteúdo do link:reference-permissions-gcp.html["Permissões de conta de serviço para o conetor"].
.. No Google Cloud, ative o shell da nuvem.
.. Carregue o arquivo YAML que inclui as permissões necessárias.
.. Crie uma função personalizada usando o `gcloud iam roles create` comando.
+
O exemplo a seguir cria uma função chamada "Connector" no nível do projeto:

+
`gcloud iam roles create connector --project=myproject --file=connector.yaml`

+
https://cloud.google.com/iam/docs/creating-custom-roles#iam-custom-roles-create-gcloud["Google Cloud docs: Criando e gerenciando funções personalizadas"^]



. Crie uma conta de serviço no Google Cloud e atribua a função à conta de serviço:
+
.. No serviço IAM e Admin, selecione *Contas de serviço > criar conta de serviço*.
.. Insira os detalhes da conta de serviço e selecione *criar e continuar*.
.. Selecione a função que você acabou de criar.
.. Conclua as etapas restantes para criar a função.
+
https://cloud.google.com/iam/docs/creating-managing-service-accounts#creating_a_service_account["Google Cloud docs: Criando uma conta de serviço"^]



. Se você planeja implantar sistemas Cloud Volumes ONTAP em projetos diferentes do projeto em que o conetor reside, precisará fornecer à conta de serviço do conetor acesso a esses projetos.
+
Por exemplo, digamos que o conetor está no projeto 1 e você deseja criar sistemas Cloud Volumes ONTAP no projeto 2. Você precisará conceder acesso à conta de serviço no projeto 2.

+
.. No serviço IAM e Admin, selecione o projeto Google Cloud onde você deseja criar sistemas Cloud Volumes ONTAP.
.. Na página *IAM*, selecione *Grant Access* e forneça os detalhes necessários.
+
*** Introduza o e-mail da conta de serviço do conetor.
*** Selecione a função personalizada do conetor.
*** Selecione *Guardar*.




+
Para obter mais detalhes, consulte https://cloud.google.com/iam/docs/granting-changing-revoking-access#grant-single-role["Documentação do Google Cloud"^]



.Resultado
A conta de serviço da VM Connector é configurada.



== Etapa 5: Configurar permissões de VPC compartilhadas

Se você estiver usando uma VPC compartilhada para implantar recursos em um projeto de serviço, precisará preparar suas permissões.

Essa tabela é para referência e seu ambiente deve refletir a tabela de permissões quando a configuração do IAM estiver concluída.

.Exibir permissões de VPC compartilhadas
[%collapsible]
====
[cols="10,10,10,18,18,34"]
|===
| Identidade | Criador | Hospedado em | Permissões do projeto de serviço | Permissões do projeto de host | Finalidade 


| Conta Google para implantar o conetor | Personalizado | Projeto de Serviço  a| 
link:task-install-connector-google-bluexp-gcloud.html#step-2-set-up-permissions-to-create-the-connector["Política de implantação do conetor"]
 a| 
compute.networkUser
| Implantando o conetor no projeto de serviço 


| Conta de serviço do conetor | Personalizado | Projeto de serviço  a| 
link:reference-permissions-gcp.html["Política de conta de serviço do conetor"]
| compute.networkUser deploymentmanager.editor | Implantação e manutenção de Cloud Volumes ONTAP e serviços no projeto de serviço 


| Conta de serviço Cloud Volumes ONTAP | Personalizado | Projeto de serviço | Membro Storage.admin: Conta de serviço BlueXP  como serviceAccount.user | N/A. | (Opcional) para disposição de dados em categorias e backup e recuperação do BlueXP  


| Agente de serviços de APIs do Google | Google Cloud | Projeto de serviço  a| 
(Predefinição) Editor
 a| 
compute.networkUser
| Interage com as APIs do Google Cloud em nome da implantação. Permite que o BlueXP  utilize a rede partilhada. 


| Conta de serviço padrão do Google Compute Engine | Google Cloud | Projeto de serviço  a| 
(Predefinição) Editor
 a| 
compute.networkUser
| Implanta instâncias do Google Cloud e infraestrutura de computação em nome da implantação. Permite que o BlueXP  utilize a rede partilhada. 
|===
Notas:

. Deploymentmanager.editor só é necessário no projeto host se você não estiver passando regras de firewall para a implantação e estiver escolhendo permitir que o BlueXP  as crie para você. O BlueXP  criará uma implantação no projeto host que contém a regra de firewall VPC0 se nenhuma regra for especificada.
. Firewall.create e firewall.delete só são necessários se você não estiver passando regras de firewall para a implantação e estiver escolhendo permitir que o BlueXP  as crie para você. Essas permissões residem no arquivo .yaml da conta do BlueXP . Se você estiver implantando um par de HA usando uma VPC compartilhada, essas permissões serão usadas para criar as regras de firewall para VPC1, 2 e 3. Para todas as outras implantações, essas permissões também serão usadas para criar regras para VPC0.
. Para categorização de dados, a conta de serviço de disposição em categorias precisa ter a função serviceAccount.user na conta de serviço, não apenas no nível do projeto. Atualmente, se você atribuir serviceAccount.user no nível do projeto, as permissões não serão exibidas quando você consultar a conta de serviço com getIAMPolicy.


====


== Etapa 6: Habilite as APIs do Google Cloud

Várias APIs do Google Cloud devem estar ativadas antes de implantar sistemas Cloud Volumes ONTAP no Google Cloud.

.Passo
. Ative as seguintes APIs do Google Cloud em seu projeto:
+
** API do Cloud Deployment Manager V2
** API Cloud Logging
** API do Cloud Resource Manager
** API do mecanismo de computação
** API de gerenciamento de identidade e acesso (IAM)
** API do Cloud Key Management Service (KMS)
+
(Necessário somente se você estiver planejando usar o backup e a recuperação do BlueXP  com chaves de criptografia gerenciadas pelo cliente (CMEK))





https://cloud.google.com/apis/docs/getting-started#enabling_apis["Documentação do Google Cloud: Habilitando APIs"^]



== Passo 7: Instale o conetor

Após a conclusão dos pré-requisitos, você pode instalar manualmente o software em seu próprio host Linux.

.Antes de começar
Você deve ter o seguinte:

* Root Privileges para instalar o conetor.
* Detalhes sobre um servidor proxy, se for necessário um proxy para acesso à Internet a partir do conetor.
+
Você tem a opção de configurar um servidor proxy após a instalação, mas isso requer a reinicialização do conetor.

+
Observe que o BlueXP  não oferece suporte a servidores proxy transparentes.

* Um certificado assinado pela CA, se o servidor proxy usar HTTPS ou se o proxy for um proxy intercetor.


.Sobre esta tarefa
O instalador disponível no site de suporte da NetApp pode ser uma versão anterior. Após a instalação, o conetor se atualiza automaticamente se uma nova versão estiver disponível.

.Passos
. Se as variáveis de sistema _http_proxy_ ou _https_proxy_ estiverem definidas no host, remova-as:
+
[source, cli]
----
unset http_proxy
unset https_proxy
----
+
Se você não remover essas variáveis do sistema, a instalação falhará.

. Faça o download do software Connector do https://mysupport.netapp.com/site/products/all/details/cloud-manager/downloads-tab["Site de suporte da NetApp"^]e copie-o para o host Linux.
+
Você deve baixar o instalador do conetor "online" destinado a ser usado em sua rede ou na nuvem. Um instalador "offline" separado está disponível para o conetor, mas só é suportado com implantações de modo privado.

. Atribua permissões para executar o script.
+
[source, cli]
----
chmod +x BlueXP-Connector-Cloud-<version>
----
+
Onde <version> é a versão do conetor que você baixou.

. Execute o script de instalação.
+
[source, cli]
----
 ./BlueXP-Connector-Cloud-<version> --proxy <HTTP or HTTPS proxy server> --cacert <path and file name of a CA-signed certificate>
----
+
Os parâmetros --proxy e --cacert são opcionais. Se você tiver um servidor proxy, será necessário inserir os parâmetros como mostrado. O instalador não solicita que você forneça informações sobre um proxy.

+
Aqui está um exemplo do comando usando ambos os parâmetros opcionais:

+
[source, cli]
----
 ./BlueXP-Connector-Cloud-v3.9.40--proxy https://user:password@10.0.0.30:8080/ --cacert /tmp/cacert/certificate.cer
----
+
--proxy configura o conetor para usar um servidor proxy HTTP ou HTTPS usando um dos seguintes formatos:

+
** \http://address:port
** \http://user-name:password@address:port
** \http://domain-name%92user-name:password@address:port
** \https://address:port
** \https://user-name:password@address:port
** \https://domain-name%92user-name:password@address:port
+
Observe o seguinte:

+
*** O usuário pode ser um usuário local ou usuário de domínio.
*** Para um usuário de domínio, você deve usar o código ASCII para a como mostrado acima.
*** O BlueXP  não suporta nomes de usuário ou senhas que incluem o caractere A.
*** Se a senha incluir qualquer um dos seguintes carateres especiais, você deve escapar desse caractere especial, prependendo-o com uma barra invertida: & Ou !
+
Por exemplo:

+
\http://bxpproxyuser:netapp1\!@address:3128





+
--cacert especifica um certificado assinado pela CA a ser usado para acesso HTTPS entre o conetor e o servidor proxy. Este parâmetro só é necessário se especificar um servidor proxy HTTPS ou se o proxy for um proxy intercetor.

. Aguarde até que a instalação seja concluída.
+
No final da instalação, o serviço de conetor (occm) será reiniciado duas vezes se você tiver especificado um servidor proxy.

. Abra um navegador da Web a partir de um host que tenha uma conexão com a máquina virtual do conetor e insira o seguinte URL:
+
https://_ipaddress_[]

. Depois de iniciar sessão, configure o conetor:
+
.. Especifique a organização BlueXP  a associar ao conetor.
.. Introduza um nome para o sistema.
.. Em *você está executando em um ambiente seguro?* mantenha o modo restrito desativado.
+
Você deve manter o modo restrito desativado porque estas etapas descrevem como usar o BlueXP  no modo padrão. Você deve habilitar o modo restrito somente se tiver um ambiente seguro e quiser desconetar essa conta dos serviços de back-end do BlueXP . Se for esse o casolink:task-quick-start-restricted-mode.html["Siga os passos para começar a utilizar o BlueXP  no modo restrito"], .

.. Selecione *vamos começar*.




.Resultado
O conetor está agora instalado e está configurado com a sua organização BlueXP .

Se você tiver buckets do Google Cloud Storage na mesma conta do Google Cloud onde criou o conetor, verá um ambiente de trabalho do Google Cloud Storage aparecer automaticamente na tela do BlueXP . https://docs.netapp.com/us-en/bluexp-google-cloud-storage/index.html["Saiba como gerenciar o Google Cloud Storage da BlueXP "^]



== Passo 8: Forneça permissões para o BlueXP 

Você precisa fornecer ao BlueXP  as permissões do Google Cloud que você configurou anteriormente. O fornecimento de permissões permite que o BlueXP  gerencie sua infraestrutura de dados e armazenamento no Google Cloud.

.Passos
. Vá para o portal do Google Cloud e atribua a conta de serviço à instância da VM Connector.
+
https://cloud.google.com/compute/docs/access/create-enable-service-accounts-for-instances#changeserviceaccountandscopes["Documentação do Google Cloud: Alterando a conta de serviço e os escopos de acesso para uma instância"^]

. Se você quiser gerenciar recursos em outros projetos do Google Cloud, conceda acesso adicionando a conta de serviço com a função BlueXP  a esse projeto. Você precisará repetir esta etapa para cada projeto.


.Resultado
O BlueXP  agora tem as permissões necessárias para executar ações no Google Cloud em seu nome.
