= Conector 3.9.53
:allow-uri-read: 




=== Conector 3.9.53

Esta versão do BlueXP Connector inclui melhorias de segurança e correções de bugs.

No momento, a versão 3.9.53 está disponível para modo padrão e modo restrito.



=== Gerenciamento de identidade e acesso do BlueXP  (IAM)



==== Autenticação multifator (MFA)

Usuários não federados agora podem habilitar a autenticação multifator (MFA) para suas contas BlueXP, aumentando a segurança da conta. Os administradores do BlueXP podem gerenciar as configurações de MFA para seus usuários, redefinindo ou desativando a MFA para usuários individuais, conforme necessário.

link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-user-settings.html#task-user-mfa["Saiba mais sobre como configurar a autenticação multifator para você."^] link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-iam-manage-members.permission.html#manage-mfa["Saiba mais sobre como gerenciar a autenticação multifator para usuários."^]



=== Workloads

Agora você pode visualizar e excluir credenciais do Amazon FSx para NetApp ONTAP na página Credenciais no BlueXP.
