= Conetor 3.9.51
:allow-uri-read: 




=== Conetor 3.9.51

Esta versão do conetor BlueXP  inclui pequenas melhorias de segurança e correções de bugs.

Neste momento, a versão 3.9.51 está disponível para o modo padrão e modo restrito.



==== Pontos de extremidade seguros para downloads de conetores agora compatíveis com backup e recuperação e proteção contra ransomware

Se você estiver usando a proteção de backup e recuperação ou ransomware, agora você pode usar endpoints seguros para downloads de conetores. link:https://docs.netapp.com/us-en/bluexp-setup-admin/whats-new.html#new-secure-endpoints-to-obtain-connector-images["Saiba mais sobre endpoints seguros para downloads de conetores."^]



=== Gerenciamento de identidade e acesso do BlueXP  (IAM)

* Os usuários sem o administrador Org ou pasta ou administrador de projeto devem ter uma função de proteção contra ransomware para ter acesso à proteção contra ransomware. Você pode atribuir a um usuário uma de duas funções: Administrador de proteção contra ransomware ou visualizador de proteção contra ransomware.
* Os usuários sem o administrador da organização ou pasta ou administrador do projeto devem ter uma função do Keystone para ter acesso ao Keystone. Você pode atribuir a um usuário uma de duas funções: Administrador do Keystone ou visualizador do Keystone.
+
link:https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["Saiba mais sobre as funções de acesso."^]

* Se você tiver a função de administrador de Org ou pasta ou administrador de projeto, agora poderá associar uma assinatura do Keystone a um projeto do IAM. A associação de uma assinatura do Keystone a um projeto do IAM permite que você controle o acesso ao Keystone no BlueXP .

