= 
:allow-uri-read: 


Crie uma função e aplique-a a uma conta de serviço que você usará para a instância de VM Connector.

.Passos
. Crie uma função personalizada no Google Cloud:
+
.. Crie um arquivo YAML que inclua as permissões definidas no link:reference-permissions-gcp.html["Política de conetores para Google Cloud"].
.. No Google Cloud, ative o shell da nuvem.
.. Carregue o arquivo YAML que inclui as permissões necessárias para o conetor.
.. Crie uma função personalizada usando o `gcloud iam roles create` comando.
+
O exemplo a seguir cria uma função chamada "Connector" no nível do projeto:

+
[source, gcloud]
----
gcloud iam roles create connector --project=myproject --file=connector.yaml
----
+
https://cloud.google.com/iam/docs/creating-custom-roles#iam-custom-roles-create-gcloud["Google Cloud docs: Criando e gerenciando funções personalizadas"^]



. Crie uma conta de serviço no Google Cloud:
+
.. No serviço IAM e Admin, selecione *Contas de serviço > criar conta de serviço*.
.. Insira os detalhes da conta de serviço e selecione *criar e continuar*.
.. Selecione a função que você acabou de criar.
.. Conclua as etapas restantes para criar a função.
+
https://cloud.google.com/iam/docs/creating-managing-service-accounts#creating_a_service_account["Google Cloud docs: Criando uma conta de serviço"^]





.Resultado
Agora você tem uma conta de serviço que pode atribuir à instância de VM Connector.
