= 
:allow-uri-read: 


Se você estiver usando uma VPC compartilhada para implantar recursos em um projeto de serviço, precisará preparar suas permissões.

Essa tabela é para referência e seu ambiente deve refletir a tabela de permissões quando a configuração do IAM estiver concluída.

.Exibir permissões de VPC compartilhadas
[%collapsible]
====
[cols="10,10,10,18,18,34"]
|===
| Identidade | Criador | Hospedado em | Permissões do projeto de serviço | Permissões do projeto de host | Finalidade 


| Conta Google para implantar o conetor | Personalizado | Projeto de Serviço  a| 
link:task-install-connector-google-bluexp-gcloud.html#step-2-set-up-permissions-to-create-the-connector["Política de implantação do conetor"]
 a| 
compute.networkUser
| Implantando o conetor no projeto de serviço 


| Conta de serviço do conetor | Personalizado | Projeto de serviço  a| 
link:reference-permissions-gcp.html["Política de conta de serviço do conetor"]
| compute.networkUser deploymentmanager.editor | Implantação e manutenção de Cloud Volumes ONTAP e serviços no projeto de serviço 


| Conta de serviço Cloud Volumes ONTAP | Personalizado | Projeto de serviço | Membro Storage.admin: Conta de serviço BlueXP  como serviceAccount.user | N/A. | (Opcional) para disposição de dados em categorias e backup e recuperação do BlueXP  


| Agente de serviços de APIs do Google | Google Cloud | Projeto de serviço  a| 
(Predefinição) Editor
 a| 
compute.networkUser
| Interage com as APIs do Google Cloud em nome da implantação. Permite que o BlueXP  utilize a rede partilhada. 


| Conta de serviço padrão do Google Compute Engine | Google Cloud | Projeto de serviço  a| 
(Predefinição) Editor
 a| 
compute.networkUser
| Implanta instâncias do Google Cloud e infraestrutura de computação em nome da implantação. Permite que o BlueXP  utilize a rede partilhada. 
|===
Notas:

. Deploymentmanager.editor só é necessário no projeto host se você não estiver passando regras de firewall para a implantação e estiver escolhendo permitir que o BlueXP  as crie para você. O BlueXP  criará uma implantação no projeto host que contém a regra de firewall VPC0 se nenhuma regra for especificada.
. Firewall.create e firewall.delete só são necessários se você não estiver passando regras de firewall para a implantação e estiver escolhendo permitir que o BlueXP  as crie para você. Essas permissões residem no arquivo .yaml da conta do BlueXP . Se você estiver implantando um par de HA usando uma VPC compartilhada, essas permissões serão usadas para criar as regras de firewall para VPC1, 2 e 3. Para todas as outras implantações, essas permissões também serão usadas para criar regras para VPC0.
. Para categorização de dados, a conta de serviço de disposição em categorias precisa ter a função serviceAccount.user na conta de serviço, não apenas no nível do projeto. Atualmente, se você atribuir serviceAccount.user no nível do projeto, as permissões não serão exibidas quando você consultar a conta de serviço com getIAMPolicy.


====