= 
:allow-uri-read: 


Dependendo do seu sistema operacional, o Podman ou o Docker Engine são necessários antes de instalar o conetor.

* O Podman é necessário para o Red Hat Enterprise Linux 8 e 9.
+
<<podman-versions,Veja as versões do Podman suportadas pelo BlueXP >>.

* Docker Engine é necessário para o Ubuntu.
+
<<podman-versions,Veja as versões do Docker Engine que o BlueXP  suporta>>.



.Passos
[role="tabbed-block"]
====
.Podman
--
Siga estas etapas para instalar o Podman e configurá-lo para atender aos seguintes requisitos:

* Habilitar e iniciar o serviço podman.socket
* Instale o python3
* Instale o pacote podman-compose versão 1.0.6
* Adicione podman-compose à variável de ambiente PATH



NOTE: Ao usar o Podman, ajuste a porta de serviço aardvark-dns (padrão: 53) após instalar o Conector para evitar conflitos com a porta DNS no host. Siga as instruções para configurar a porta.

.Passos
. Remova o pacote podman-docker se ele estiver instalado no host.
+
[source, cli]
----
dnf remove podman-docker
rm /var/run/docker.sock
----
. Instale o Podman.
+
O Podman está disponível nos repositórios oficiais do Red Hat Enterprise Linux.

+
Para Red Hat Enterprise Linux 9:

+
[source, cli]
----
sudo dnf install podman-2:<version>
----
+
Onde o <version> é a versão suportada do Podman que você está instalando. <<podman-versions,Veja as versões do Podman suportadas pelo BlueXP >>.

+
Para Red Hat Enterprise Linux 8:

+
[source, cli]
----
sudo dnf install podman-3:<version>
----
+
Onde o <version> é a versão suportada do Podman que você está instalando. <<podman-versions,Veja as versões do Podman suportadas pelo BlueXP >>.

. Ative e inicie o serviço podman.socket.
+
[source, cli]
----
sudo systemctl enable --now podman.socket
----
. Instale o python3.
+
[source, cli]
----
sudo dnf install python3
----
. Instale o pacote do repositório EPEL se ainda não estiver disponível no seu sistema.
+
Esta etapa é necessária porque o podman-compose está disponível no repositório extra Packages for Enterprise Linux (EPEL).

+
Para Red Hat Enterprise Linux 9:

+
[source, cli]
----
sudo dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
----
+
Para Red Hat Enterprise Linux 8:

+
[source, cli]
----
sudo dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
----
. Instale o pacote podman-compose 1,0.6.
+
[source, cli]
----
sudo dnf install podman-compose-1.0.6
----
+

NOTE: Usar o `dnf install` comando atende ao requisito para adicionar podman-compose à variável de ambiente PATH. O comando installation adiciona podman-compose ao /usr/bin, que já está incluído na `secure_path` opção no host.



--
.Docker Engine
--
Siga a documentação do Docker para instalar o Docker Engine.

.Passos
. https://docs.docker.com/engine/install/["Veja as instruções de instalação do Docker"^]
+
Certifique-se de seguir as etapas para instalar uma versão específica do Docker Engine. Instalar a versão mais recente irá instalar uma versão do Docker que o BlueXP  não suporta.

. Verifique se o Docker está ativado e em execução.
+
[source, cli]
----
sudo systemctl enable docker && sudo systemctl start docker
----


--
====